In [ ]:
import pandas as pd
df = pd.read_csv('/messy_sales_data.csv')
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      20 non-null     int64
 1   name             19 non-null     object
 2   age              17 non-null     float64
 3   city             20 non-null     object
 4   signup_date      20 non-null     object
 5   purchase_amount  18 non-null     float64
 6   category         20 non-null     object
 7   email            19 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.4+ KB

customer_id        0
name               1
age                3
city               0
signup_date        0
purchase_amount    2
category           0
email              1
dtype: int64

In [ ]:
df1 = df.dropna()

In [ ]:
df['age'] = df['age'].fillna(df['age'].mean())
df

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.000000,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.000000,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.000000,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,37.352941,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.000000,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.000000,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
6,7,Anjali Nair,37.352941,Chennai,15-03-2023,1050.0,groceries,anjali.nair@email.com
7,8,Karan Mehta,38.000000,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
8,9,Neha Joshi,41.000000,Bangalore,2023-03-01,NaN,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,-5.000000,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,22.000000,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,36.000000,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,150.000000,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,28.000000,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
14,15,Kavita Rao,37.352941,Mumbai,2023-05-05,NaN,Electronics,kavita.rao@email.com
15,16,Farhan Ali,31.000000,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,31.000000,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,27.000000,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,39.000000,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com
19,20,NaN,34.000000,Mumbai,2023-06-15,890.0,Clothing,NaN

In [ ]:
x = df['age'].to_numpy()
x

array([ 25.        ,  32.        ,  32.        ,  37.35294118,
        45.        ,  29.        ,  37.35294118,  38.        ,
        41.        ,  -5.        ,  22.        ,  36.        ,
       150.        ,  28.        ,  37.35294118,  31.        ,
        31.        ,  27.        ,  39.        ,  34.        ])

In [ ]:
n = (x-x.min())/(x.max()-x.min())
df['age'] = n
df

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,0.193548,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,0.238710,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,0.238710,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,0.273245,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,0.322581,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,0.219355,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
6,7,Anjali Nair,0.273245,Chennai,15-03-2023,1050.0,groceries,anjali.nair@email.com
7,8,Karan Mehta,0.277419,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
8,9,Neha Joshi,0.296774,Bangalore,2023-03-01,NaN,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,0.000000,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,0.174194,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,0.264516,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,1.000000,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,0.212903,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
14,15,Kavita Rao,0.273245,Mumbai,2023-05-05,NaN,Electronics,kavita.rao@email.com
15,16,Farhan Ali,0.232258,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,0.232258,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,0.206452,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,0.283871,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com
19,20,NaN,0.251613,Mumbai,2023-06-15,890.0,Clothing,NaN